---
version: "3.8"

networks:
  proxy:
    external: true
    
services:
  tech-grow-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-grow-frontend
    ports: [4173:4173]
